# Generated by Django 5.1.1 on 2024-09-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='price',
            field=models.TextField(),
        ),
    ]
